version: '3.8'

services:
  webapp:
    build: .
    image: webapp:latest
    ports:
      - "3000:3000"
    environment:
      - MYSQL_URL=mysql://user:password@database:3306/webapp_db 
    depends_on:
      - database
    restart: always

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: webapp_db           
      MYSQL_USER: user                    
      MYSQL_PASSWORD: password            
    volumes:
      - db_data:/var/lib/mysql            
    restart: always

  tests:
    image: webapp:latest
    environment:
      API_URL: http://webapp:3000 
    depends_on:
      - webapp
      - database
    command: yarn test
    networks:
      - default

volumes:
  db_data: