---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Check out repository code
      #   uses: actions/checkout@v1 #v2

      - name: Set up Node.js 20
        uses: actions/setup-node@v2 #v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install
      
      - name: Running lint
        env:
          ESLINT_USE_FLAT_CONFIG: false
        run: yarn lint

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # v3

      - name: Build the Docker image
        uses: docker/build-push-action@v4 # v5
        with:
          context: .
          file: ./Dockerfile
          tags: siebevdd/webapp:latest
          push: true